#!/bin/sh

git pull
cd hackathon
npm run build
retVal=$?
if [ $retVal -ne 0 ]; then
  echo "Attempting to wipe node_modules and rerun build"
  npm ci
  npm run build
fi
cd -
git add -A && git commit -m "Heroku Deployment checkin" && git push
./mvnw clean install

git push heroku main