#!/bin/sh

cd hackathon
npm run build
retVal=$?
if [ $retVal -ne 0 ]; then
  echo "Attempting to wipe node_modules and rerun build"
  npm ci
  npm run build
fi
cd -
git commit -a -m "Static Checkin for Heroku Deploy"
./mvnw clean install

git push heroku main